import { IsArray, IsBoolean, IsNotEmpty, IsOptional, IsString } from 'class-validator';

/**
 * DTO for creating Usuario
 * Auto-generated by ELEVARE DTO Generator
 */
export class CreateUsuarioDto {
  @IsNotEmpty()
  @IsString()
  email!: string;

  @IsNotEmpty()
  @IsString()
  senha!: string;

  @IsNotEmpty()
  @IsString()
  nome!: string;

  @IsNotEmpty()
  @IsString()
  clinicId!: string;

  @IsNotEmpty()
  @IsArray()
  roles!: string[];

  @IsNotEmpty()
  @IsBoolean()
  ativo!: boolean;

}
