import { IsString, IsNotEmpty, IsOptional } from 'class-validator';

/**
 * DTO for creating Bloqueio
 * Auto-generated by ELEVARE DTO Generator
 */
export class CreateBloqueioDto {
  @IsNotEmpty()
  @IsString()
  clinicId!: string;

  @IsNotEmpty()
  @IsString()
  data!: string;

  @IsNotEmpty()
  @IsString()
  startTime!: string;

  @IsNotEmpty()
  @IsString()
  endTime!: string;

  @IsNotEmpty()
  @IsString()
  tipo!: 'almoco' | 'feriado' | 'sabado' | 'intervalo' | 'personalizado';

  @IsNotEmpty()
  @IsString()
  motivo!: string;

  @IsNotEmpty()
  @IsString()
  recorrente!: boolean;

  @IsNotEmpty()
  @IsString()
  ateData!: string;

}
