import { IsNotEmpty, IsNumber, IsOptional, IsString } from 'class-validator';

/**
 * DTO for creating Agendamento
 * Auto-generated by ELEVARE DTO Generator
 */
export class CreateAgendamentoDto {
  @IsNotEmpty()
  @IsString()
  clinicId!: string;

  @IsNotEmpty()
  @IsString()
  nomePaciente!: string;

  @IsNotEmpty()
  @IsString()
  telefoneE164!: string;

  @IsNotEmpty()
  @IsString()
  procedimento!: string;

  @IsNotEmpty()
  @IsString()
  startISO!: string;

  @IsNotEmpty()
  @IsNumber()
  duracaoMinutos!: number;

  @IsNotEmpty()
  @IsString()
  status!: 'agendado' | 'confirmado' | 'compareceu' | 'no-show' | 'cancelado';

  @IsNotEmpty()
  @IsString()
  observacoes!: string;

  @IsNotEmpty()
  @IsString()
  leadId!: string;

}
