import { IsString, IsNotEmpty, IsOptional } from 'class-validator';

/**
 * DTO for creating Event
 * Auto-generated by ELEVARE DTO Generator
 */
export class CreateEventDto {
  @IsNotEmpty()
  @IsString()
  clinicId!: string;

  @IsNotEmpty()
  @IsString()
  agendamentoId!: string;

  @IsNotEmpty()
  @IsString()
  mensagemId!: string;

  @IsNotEmpty()
  @IsString()
  campanhaId!: string;

  @IsNotEmpty()
  @IsString()
  indicacaoId!: string;

  @IsNotEmpty()
  @IsString()
  metadata!: Record<string, any>;

  @IsNotEmpty()
  @IsString()
  before!: Record<string, any>;

  @IsNotEmpty()
  @IsString()
  after!: Record<string, any>;

  @IsNotEmpty()
  @IsString()
  userId!: string;

  @IsNotEmpty()
  @IsString()
  ipAddress!: string;

  @IsNotEmpty()
  @IsString()
  source!: string;

  @IsNotEmpty()
  @IsString()
  processed!: boolean;

}
