import { IsString, IsNotEmpty, IsOptional } from 'class-validator';

/**
 * DTO for creating Evento
 * Auto-generated by ELEVARE DTO Generator
 */
export class CreateEventoDto {
  @IsNotEmpty()
  @IsString()
  tipo!: string;

  @IsNotEmpty()
  @IsString()
  descricao!: string;

}
