import { IsString, IsNotEmpty, IsOptional } from 'class-validator';

/**
 * DTO for creating Campanha
 * Auto-generated by ELEVARE DTO Generator
 */
export class CreateCampanhaDto {
  @IsNotEmpty()
  @IsString()
  titulo!: string;

  @IsNotEmpty()
  @IsString()
  objetivo!: string;

  @IsNotEmpty()
  @IsString()
  ativo!: boolean;

}
