import { IsNotEmpty, IsNumber, IsOptional, IsString } from 'class-validator';

/**
 * DTO for creating Indicacao
 * Auto-generated by ELEVARE DTO Generator
 */
export class CreateIndicacaoDto {
  @IsNotEmpty()
  @IsString()
  indicadorId!: string;

  @IsNotEmpty()
  @IsString()
  clinicId!: string;

  @IsNotEmpty()
  @IsString()
  nomeIndicado!: string;

  @IsNotEmpty()
  @IsString()
  telefoneIndicado!: string;

  @IsNotEmpty()
  @IsString()
  emailIndicado!: string;

  @IsNotEmpty()
  @IsString()
  status!: 'pendente' | 'contatado' | 'agendado' | 'compareceu' | 'cancelado';

  @IsNotEmpty()
  @IsNumber()
  pontosGanhos!: number;

  @IsNotEmpty()
  @IsString()
  agendamentoId!: string;

}
