import { IsString, IsNotEmpty, IsOptional } from 'class-validator';

/**
 * DTO for creating Recompensa
 * Auto-generated by ELEVARE DTO Generator
 */
export class CreateRecompensaDto {
  @IsNotEmpty()
  @IsString()
  clinicId!: string;

  @IsNotEmpty()
  @IsString()
  pontosAcumulados!: number;

  @IsNotEmpty()
  @IsString()
  sessoesGratisDisponiveis!: number;

  @IsNotEmpty()
  @IsString()
  historicoIndicacoes!: string[];

  @IsNotEmpty()
  @IsString()
  ultimaResgate!: Date;

}
