import { IsArray, IsDateString, IsNotEmpty, IsNumber, IsOptional, IsString } from 'class-validator';

/**
 * DTO for creating Recompensa
 * Auto-generated by ELEVARE DTO Generator
 */
export class CreateRecompensaDto {
  @IsNotEmpty()
  @IsString()
  clinicId!: string;

  @IsNotEmpty()
  @IsNumber()
  pontosAcumulados!: number;

  @IsNotEmpty()
  @IsNumber()
  sessoesGratisDisponiveis!: number;

  @IsNotEmpty()
  @IsArray()
  historicoIndicacoes!: string[];

  @IsNotEmpty()
  @IsDateString()
  ultimaResgate!: Date;

}
