import { IsNotEmpty, IsOptional, IsString } from 'class-validator';

/**
 * DTO for creating Cliente
 * Auto-generated by ELEVARE DTO Generator
 */
export class CreateClienteDto {
  @IsNotEmpty()
  @IsString()
  nome!: string;

  @IsNotEmpty()
  @IsString()
  telefone!: string;

  @IsNotEmpty()
  @IsString()
  dataNascimento!: string;

  @IsNotEmpty()
  @IsString()
  clinicId!: string;

}
