import { IsNotEmpty, IsOptional, IsString } from 'class-validator';

/**
 * DTO for creating WhatsAppMessage
 * Auto-generated by ELEVARE DTO Generator
 */
export class CreateWhatsAppMessageDto {
  @IsNotEmpty()
  @IsString()
  phone!: string;

  @IsNotEmpty()
  @IsString()
  message!: string;

  @IsNotEmpty()
  @IsString()
  status!: 'pending' | 'sent' | 'delivered' | 'failed' | 'responded';

  @IsNotEmpty()
  @IsString()
  providerMessageId!: string;

  @IsNotEmpty()
  @IsString()
  clinicId!: string;

}
